### ISSUE TITLE
Decide on Hosting. Is Domain name available?

### ISSUE THREAD

**Issue by TheGeneral88** [acd37/outdoorRepo#12]

**Comment by TheGeneral88** [comment]
➤ Max Wheeler commented:

I believe Alec has the domain purchased for the year, but if not we can make sure to nab it by the end of Tuesday.

**Comment by TheGeneral88** [comment]
➤ Alec Down commented:

@maxwheeler10 Nope. I don't. I currently just have it hosted on git pages.

**Comment by acd37** [comment]
Issue complete.
