### ISSUE TITLE
Decide on Name and slogan

### ISSUE THREAD

**Issue by TheGeneral88** [acd37/outdoorRepo#13]

**Comment by TheGeneral88** [comment]
➤ Alec Down commented:

outdoorRepo

**Comment by TheGeneral88** [comment]
OutdoorRepo it is then. 
Slogan?

**Comment by TheGeneral88** [comment]
➤ Max Wheeler commented:

Slogan Idea: "Get more from your gear."

**Comment by TheGeneral88** [comment]
@maxwheeler10  That's tight! I like that

**Comment by acd37** [comment]
Issue complete.
