### ISSUE TITLE
Charitable Contributions:

### ISSUE THREAD

**Issue by TheGeneral88** [acd37/outdoorRepo#17]
In lieu of (or perhaps coordination with) a point system, we can market as a Charitable site. We can allow the User to select from a list of charities, which they can change at any time. We then siphon off a portion of our affiliate profits from individual purchases and donate everything in a lump sum at the end of each month to each respective charity. This would allow us to be marketed better among other organizations/individuals (like bloggers/vloggers).

We could bolster this system by doing weekly/bimonthly/monthly raffles, where raffle tickets would be given out on a "how-much-you-spent" basis (e.g. 1 raffle ticket per $100 spent through our affiliate links).

**Comment by acd37** [comment]
Issue complete.
