### ISSUE TITLE
AvantLink+ Cj Affiliate Accounts

### ISSUE THREAD

**Issue by TheGeneral88** [acd37/outdoorRepo#27]
Set up after website is LIVE. A live website is a base requirement to even apply many affiliate programs.

**Comment by TheGeneral88** [comment]
➤ Max Wheeler commented:

We probably won't be able to get a lot of the affiliate links that we want at first, so it would be fine just to use a standard link to their websites (non-affiliate) until we can acquire links post-LIVE.

**Comment by acd37** [comment]
Issue complete.
